# Generated by Django 4.1.7 on 2023-03-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('anio_publicacion', models.DateField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('paginas', models.CharField(max_length=100, verbose_name='Pagina del Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('fecha_devolucion', models.DateField(auto_created=True)),
                ('fecha_prestamo', models.DateField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='Usuario')),
                ('password', models.IntegerField(verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libro')),
                ('id_prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prestamo')),
            ],
        ),
    ]
